[tools]
rust = "1.93.1"
yamlfmt = "0.21"

[tasks.rata]
run = "cargo run"

[tasks.fmt]
description = "Run code formatters"
run = ["cargo fmt", "yamlfmt ."]

[tasks."fmt:check"]
description = "Check code formatters"
run = ["cargo fmt --check", "yamlfmt -lint -quiet ."]

[tasks.lint]
description = "Run clippy linter"
run = "cargo clippy -- -D warnings"

[tasks.test]
depends = ["fmt:check", "lint", "test:unit", "test:integration"]
description = "Run all tests"

[tasks."test:unit"]
description = "Run unit tests"
run = "cargo test --workspace --lib --bins"

[tasks."test:integration"]
description = "Run Rust integration tests"
run = "cargo test --workspace --test '*'"
