type: object
properties:
  name:
    type: string
    description: 'N'
  schema:
    type: object
    additionalProperties: true
    description: 'S'
  type:
    type: string
    const: json_schema
    enum:
      - json_schema
    description: T
  description:
    type: string
    description: 'D'
  strict:
    type: boolean
    description: |
      Whether to enable strict schema adherence when generating the output.
      If set to true, the model will always follow the exact schema defined
      in the `schema` field. Only a subset of JSON Schema is supported when
      `strict` is `true`. To learn more, read the [Structured Outputs
      guide](/docs/guides/structured-outputs).
required:
  - name
  - schema
  - type
description: |
  JSON Schema response format. Used to generate structured JSON responses.
