type: object
properties:
  name:
    type: string
    description: 'The name of the response format. Must be a-z, A-Z, 0-9, or contain

      underscores and dashes, with a maximum length of 64.'
  schema:
    type: object
    additionalProperties: true
    description: 'The schema for the response format, described as a JSON Schema object.

      Learn how to build JSON schemas [here](https://json-schema.org/).'
  type:
    type: string
    const: json_schema
    enum:
    - json_schema
    description: The type of response format being defined. Always `json_schema`.
  description:
    type: string
    description: 'A description of what the response format is for, used by the model
      to

      determine how to respond in the format.'
  strict:
    type: boolean
    description: 'Whether to enable strict schema adherence when generating the output.

      If set to true, the model will always follow the exact schema defined

      in the `schema` field. Only a subset of JSON Schema is supported when

      `strict` is `true`. To learn more, read the [Structured Outputs

      guide](/docs/guides/structured-outputs).'
required:
- name
- schema
- type
description: 'JSON Schema response format. Used to generate structured JSON responses.

  Learn more about [Structured Outputs](/docs/guides/structured-outputs).'
