type: object
properties:
  type:
    type: string
    const: local
    enum:
      - local
    description: E
required:
  - type
description: |
  Represents the use of a local environment to perform shell actions.
