oneOf:
- type: object
  properties:
    type:
      type: string
      const: text
  required:
  - type
- type: object
  properties:
    type:
      type: string
      const: json_object
  required:
  - type
- allOf:
  - $ref: "../schemas/ResponseFormatJsonSchema.yaml"
  - type: object
    properties:
      type:
        type: string
        const: json_schema
    required:
    - type
